#compdef melker melker.ts
# Zsh completion for melker
# Generated by scripts/generate-completions.ts — do not edit manually
#
# Usage: Place in your $fpath (e.g. ~/.zsh/completions/_melker)
# Or source directly: source completions/melker.zsh

_melker() {
    _arguments -s \
        '--allow-ai[Allow AI tools (ffmpeg, openrouter.ai)]' \
        '--allow-all[Allow all permissions]' \
        '--allow-browser[Allow opening browser]' \
        '--allow-clipboard[Allow clipboard access]' \
        '--allow-env[Additional environment variables to allow]:value:' \
        '--allow-ffi[Additional FFI libraries to allow]:value:' \
        '--allow-keyring[Allow keyring access]' \
        '--allow-net[Additional network hosts to allow]:value:' \
        '--allow-read[Additional read paths to allow]:value:' \
        '--allow-run[Additional commands to allow]:value:' \
        '--allow-shader[Allow shader execution]' \
        '--allow-sys[Additional system info to allow]:value:' \
        '--allow-write[Additional write paths to allow]:value:' \
        '--cache[Use bundle cache]' \
        '--cached-only[Require cached remote deps]' \
        '--clear-approvals[Clear all cached approvals]' \
        '--color[ANSI color output: auto (strip when piped), always (force colors), never (no colors)]:value:(auto always never)' \
        '--convert[Convert markdown to .melker (stdout)]' \
        '--deny-ai[Deny AI tools]' \
        '--deny-all[Deny all permissions]' \
        '--deny-browser[Deny opening browser]' \
        '--deny-clipboard[Deny clipboard access]' \
        '--deny-env[Environment variables to deny]:value:' \
        '--deny-ffi[FFI libraries to deny]:value:' \
        '--deny-keyring[Deny keyring access]' \
        '--deny-net[Network hosts to deny]:value:' \
        '--deny-read[Read paths to deny]:value:' \
        '--deny-run[Commands to deny]:value:' \
        '--deny-shader[Deny shader execution]' \
        '--deny-sys[System info to deny]:value:' \
        '--deny-write[Write paths to deny]:value:' \
        '--gfx-mode[Graphics rendering: sextant (default), quadrant (2x2 Unicode blocks), block (colored spaces), pattern (ASCII spatial), luma (ASCII brightness), sixel (true pixels), kitty (kitty protocol), iterm2 (iTerm2 protocol), hires (auto: kitty/sixel/iterm2/sextant), isolines (contour lines), isolines-filled (contour lines with fill)]:value:(sextant quadrant halfblock block pattern luma sixel kitty iterm2 hires isolines isolines-filled)' \
        '--headless[Run without terminal]' \
        '--help[Show help message]' \
        '--inspect[Enable V8 inspector]' \
        '--inspect-brk[V8 inspector, break at start]' \
        '--inspect-wait[V8 inspector, wait for connection]' \
        '--interactive[Force interactive TUI mode even when stdout is not a TTY]' \
        '--lint[Enable lint validation]' \
        '--log-file[Log file path]:value:' \
        '--log-level[Log verbosity]:value:(TRACE DEBUG INFO WARN ERROR)' \
        '--lsp[Start Language Server Protocol server]' \
        '--muted[Mute all audio playback globally]' \
        '--no-alt-screen[Use alternate screen buffer]' \
        '--no-animate-gif[Animate GIF images (disable with MELKER_NO_ANIMATE_GIF=1 or --no-animate-gif)]' \
        '--no-check[Skip type checking]' \
        '--no-console-override[Disable console.log redirect to logger]' \
        '--no-load[Skip loading persisted state]' \
        '--no-lock[Disable lockfile]' \
        '--persist[Enable state persistence]' \
        '--print-config[Print current config and exit]' \
        '--print-json[Display JSON serialization and exit]' \
        '--print-tree[Display element tree and exit]' \
        '--quiet[Suppress diagnostic output]' \
        '--reload[Reload remote modules]' \
        '--revoke-approval[Revoke cached approval for path]:value:' \
        '--schema[Output component schema and exit]' \
        '--server[Enable the remote viewing server]' \
        '--server-allow-input[Allow input from server clients]' \
        '--server-port[WebSocket server port]:value:' \
        '--server-token[Server connection token (auto-generated if not specified)]:value:' \
        '--show-approval[Show cached approval for path]:value:' \
        '--show-policy[Display app policy and exit]' \
        '--stdout[Output buffer to stdout after timeout (no terminal control)]' \
        '--stdout-height[Output height in rows (default: terminal height)]:value:' \
        '--stdout-timeout[Milliseconds to wait before printing buffer (default: 500)]:value:' \
        '--stdout-trim[Trim stdout output: none (default), right (trailing spaces), bottom (trailing newlines), both]:value:(none right bottom both)' \
        '--stdout-width[Output width in columns (default: terminal width)]:value:' \
        '--test-sextant[Print sextant test pattern and exit]' \
        '--theme[Color theme]:value:' \
        '--theme-file[Path to custom theme CSS file (overrides theme selection)]:value:' \
        '--trust[Run with full permissions]' \
        '--verbose[Verbose output]' \
        '--watch[Watch file for changes and auto-reload]' \
        '-h[Show help message]' \
        '-q[Suppress diagnostic output]' \
        '*:file:_files -g "*.melker *.mmd *.md"'
}

_melker "$@"
