# Bash completion for melker
# Generated by scripts/generate-completions.ts — do not edit manually
#
# Usage: source completions/melker.bash
# Or copy to /etc/bash_completion.d/melker

_melker() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # Complete flag values
    case "$prev" in
        --color)
            COMPREPLY=( $(compgen -W "auto always never" -- "$cur") )
            return 0
            ;;
        --gfx-mode)
            COMPREPLY=( $(compgen -W "sextant block pattern luma sixel kitty iterm2 hires isolines isolines-filled" -- "$cur") )
            return 0
            ;;
        --log-level)
            COMPREPLY=( $(compgen -W "TRACE DEBUG INFO WARN ERROR" -- "$cur") )
            return 0
            ;;
        --stdout-trim)
            COMPREPLY=( $(compgen -W "none right bottom both" -- "$cur") )
            return 0
            ;;
        --allow-env)
            return 0
            ;;
        --allow-ffi)
            return 0
            ;;
        --allow-net)
            return 0
            ;;
        --allow-read)
            return 0
            ;;
        --allow-run)
            return 0
            ;;
        --allow-sys)
            return 0
            ;;
        --allow-write)
            return 0
            ;;
        --deny-env)
            return 0
            ;;
        --deny-ffi)
            return 0
            ;;
        --deny-net)
            return 0
            ;;
        --deny-read)
            return 0
            ;;
        --deny-run)
            return 0
            ;;
        --deny-sys)
            return 0
            ;;
        --deny-write)
            return 0
            ;;
        --log-file)
            return 0
            ;;
        --revoke-approval)
            return 0
            ;;
        --server-port)
            return 0
            ;;
        --server-token)
            return 0
            ;;
        --show-approval)
            return 0
            ;;
        --stdout-height)
            return 0
            ;;
        --stdout-timeout)
            return 0
            ;;
        --stdout-width)
            return 0
            ;;
        --theme)
            return 0
            ;;
        --theme-file)
            return 0
            ;;
    esac

    # Complete flags
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--allow-ai --allow-all --allow-browser --allow-clipboard --allow-env --allow-ffi --allow-keyring --allow-net --allow-read --allow-run --allow-shader --allow-sys --allow-write --cache --cached-only --clear-approvals --color --convert --deny-ai --deny-all --deny-browser --deny-clipboard --deny-env --deny-ffi --deny-keyring --deny-net --deny-read --deny-run --deny-shader --deny-sys --deny-write --gfx-mode --headless --help --inspect --inspect-brk --inspect-wait --interactive --lint --log-file --log-level --lsp --muted --no-alt-screen --no-check --no-console-override --no-load --no-lock --persist --print-config --print-json --print-tree --quiet --reload --revoke-approval --schema --server --server-allow-input --server-port --server-token --show-approval --show-policy --stdout --stdout-height --stdout-timeout --stdout-trim --stdout-width --test-sextant --theme --theme-file --trust --verbose --watch -h -q" -- "$cur") )
        return 0
    fi

    # Complete .melker, .mmd, .md files
    COMPREPLY=( $(compgen -f -X '!*.@(melker|mmd|md)' -- "$cur") )
    # Also complete directories for navigation
    COMPREPLY+=( $(compgen -d -- "$cur") )
    return 0
}

complete -o default -o filenames -F _melker melker melker.ts
