// Embedded asset system — bytes stored as grayscale PNG (base64), decoded synchronously.
//
// Data lives in assets-data.ts (generated by scripts/generate-embedded-assets.ts).
// Assets are decoded lazily on first access via decodePng() and cached.

import { decodePng } from './deps.ts';
import { ASSET_DATA } from './assets-data.ts';

const _cache = new Map<string, Uint8Array>();

/** Get asset bytes. Decodes on first access, then cached. */
export function getAsset(id: string): Uint8Array {
  let data = _cache.get(id);
  if (data) return data;
  const b64 = ASSET_DATA[id];
  if (!b64) throw new Error(`Unknown embedded asset: ${id}`);
  const bin = atob(b64);
  const png = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) png[i] = bin.charCodeAt(i);
  data = new Uint8Array(decodePng(png).data);
  _cache.set(id, data);
  return data;
}

/** Get asset as text string. */
export function getAssetText(id: string): string {
  return new TextDecoder().decode(getAsset(id));
}

/** List all asset IDs, optionally filtered by prefix. */
export function getAssetIds(prefix?: string): string[] {
  const ids = Object.keys(ASSET_DATA);
  return prefix ? ids.filter((id) => id.startsWith(prefix)) : ids;
}
